=== LucasMartin8/psimulator/bp_psi/src/data/psi.dtd
<!--<?xml version="1.0" encoding="UTF-8" ?>-->
<!-- http://www.hitsw.com/xml_utilites/ -->

<!ELEMENT ip ( #PCDATA ) >

<!ELEMENT jmeno ( #PCDATA ) >

<!ELEMENT konfigurak ( pocitac+ ) >

<!ELEMENT mac ( #PCDATA ) >

<!ELEMENT pocitac ( rozhrani+ ) >
<!ATTLIST pocitac id NMTOKEN #REQUIRED >

<!ELEMENT pripojenoK ( #PCDATA ) >

<!ELEMENT rozhrani ( jmeno, ip, mac, pripojenoK ) >
<!ATTLIST rozhrani id NMTOKEN #REQUIRED >

=== LucasMartin8/psimulator/bp_psi/src/data/psi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD tady musi byt!!! -->
<!DOCTYPE konfigurak SYSTEM "psi.dtd">

<!--
Struktura xml dokumentu musi byt zachovana. Nemenit poradi elementu.
<konfigurak>
	<port></port>
	<pocitac>
		<typ></typ>
		<rozhrani>
			<jmeno></jmeno>
			<ip></ip>
			<mac></mac>
			<pripojenoK></pripojenoK>
		</rozhrani>
	</pocitac>
</konfigurak>
-->



<konfigurak>
<port>3567</port>

<pocitac id="1">
<!-- 	<typ>linux</typ> -->
	<rozhrani id="1-1">
		<jmeno>eth0</jmeno>
		<ip>143.32.125.138</ip>
		<mac>00:01:02:03:04:05</mac>
		<pripojenoK>2-2</pripojenoK>
	</rozhrani>
	<rozhrani id="1-2">
		<jmeno>eth1</jmeno>
		<ip>143.32.125.160</ip>
		<mac>0a:00:77:03:24:d5</mac>
		<pripojenoK>2-1</pripojenoK>
	</rozhrani>
</pocitac>

<pocitac id="2">
<!-- 	<typ>cisco</typ> -->
	<rozhrani id="2-1">
		<jmeno>eth0</jmeno>
		<ip>127.1.1.8</ip>
		<mac>00:0b:0c:0d:0a:01</mac>
		<pripojenoK>1-2</pripojenoK>
	</rozhrani>
	<rozhrani id="2-2">
		<jmeno>eth1</jmeno>
		<ip>192.168.1.24</ip>
		<mac>03:08:b7:30:24:e1</mac>
		<pripojenoK>1-1</pripojenoK>
	</rozhrani>
	<rozhrani id="2-3">
		<jmeno>eth2</jmeno>
		<ip>192.168.1.25</ip>
		<mac>03:08:b7:30:24:e2</mac>
		<pripojenoK>1-1</pripojenoK>
	</rozhrani>

</pocitac>


</konfigurak>
